version: '3.8'

services:
  app:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks: 
      - mysql-compose-network
    volumes:
      - db
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
    networks: 
      - mysql-compose-network
    depends_on:
      - app
  service:
    build: ./service
    command:  bash -c "npm run start:dev" 
    ports:
      - 3000:3000
    volumes:
      - .:/service
      - node_modules:/node_modules
      - db
    networks: 
      - mysql-compose-network
    depends_on:
      - db
  client:
    build: ./client
    command:  bash -c "yarn && yarn dev" 
    ports:
      - 4000:4000
    volumes:
      - .:/client
      - node_modules:/node_modules
    depends_on:
      - service

volumes:
  node_modules:
  db: 
networks:
  mysql-compose-network:
    driver: bridge