version: '3.8'

services:
  client:
    build: ./client
    container_name: next
    command:  bash -c "yarn && yarn dev" 
    ports:
      - 4000:4000
    volumes:
      - .:/client
      - node_modules:/node_modules
  service:
    build: ./service
    container_name: nest
    command:  bash -c "npm run start" 
    ports:
      - 3000:3000
    volumes:
      - .:/service/service
      - node_modules:/node_modules
    links:
      - client
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  node_modules:
  db: 
networks:
  mysql-compose-network:
    driver: bridge

